### ISSUE TITLE
Separation of interests

### ISSUE THREAD

**Issue by calanzer** [skothawala/MessageParser#1]
You're program is awesome and it's super cool how you did it in java script. One small thing you could change is in TextUtils.js you declare var TextUtils and use it in the same file, you should try to separate them into different files.

**Comment by skothawala** [comment]
I'm using TextUtils sort of like a "class". Class here is in quotations because technically Javascript doesn't have classes the same way that Java or C# does. I'm using TextUtils._method_ the same way I'd use _this_.method. However, I can't use this as it'd be undefined and hence I have to use the class name itself. I hope that makes sense.

If I'm incorrect or you have a solution to this, please feel free to open another issue with the code or make a pull request.

Thanks
