### ISSUE TITLE
Intriguing...

### ISSUE THREAD

**Issue by jthompson18** [skothawala/MessageParser#8]
@skothawala, your implementation was intriguing...
The code and tests are all well written, I'm curious as to your reasoning for javascript and node as opposed to some other webapp style? And why did you decide to fully parse the messages within node? If you were making this a full product would you still do it the same way?

For a complete product, I'd recommend using a node implementation that handles message validation and then pass the valid message to a server to parsed and then persisted. This way the performance critical bits (parsing) is done by a high performance server using a low latency language (something statically typed, like java, scala, or c++) and the less performance intensive operation (validation) is handled by the higher latency js (which is dynamically typed) within node. The validation is made more efficient with the use of regex , but they are a pain in js. Just check out the actual twitter js for more info there -> [link](https://github.com/twitter/twitter-text/blob/master/js/twitter-text.js)

**Comment by skothawala** [comment]
Thanks for asking. I used Javascript just so that I can gain more experience in the language. I agree with you that something like this (if it were ever to be a product) would be written in a low level language to improve efficiency. However, efficiency wasn't really my goal here. I personally can't see this being a product in and of itself and so I decided to do this in a "fun" language.

However, let's say for fun that I was actually writing this as a part of a bigger project, Twitter. I would write two versions of this, one client sided to provide the client with real time validation and this would have to be written in Javascript. The other version would be server sided and would make sure that someone isn't tampering requests and such. The server sided version would be written in whatever language the application server is written in. If it were written in node.js, my life just got a lot easier because I can just do require('TextUtils.js') on the application server and use an html tag to include the TextUtils.js client sided.

Also, another thing to consider: although a low latency language might be extremely helpful for parsing large amounts of data, keep in mind tweets are relatively small (even in abundant amounts) and is the overhead of writing a custom parsing engine really necessary?

-Saad

**Comment by jthompson18** [comment]
@skothawala twitter sees an average of 500 million tweets per day. Yes a custom parsing engine is needed. Twitter has a java based one and has released the code for it. https://github.com/twitter/twitter-text/tree/master/java/src/com/twitter

**Comment by skothawala** [comment]
Hmm...I assumed they did the processing when there was a post to /statuses/update. But I can see how an engine like this would be required for their metrics and other apis.

Anyways, thanks for the information. As I mentioned earlier, I didn't really have a reason to write this in a specific language. As you pointed out, Twitter has open sources their parsing engines anyways. I wanted to write this in a language that I was not so comfortable/experienced with. I was actually considering doing this in Go, but I didn't think a week (more like the weekend) would be enough to learn enough of the language to write proper code in.

-Saad
